apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nodeapp
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: nodeapp
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: nodeapp
    spec:
      containers:
      - image: xueshanf/docker-nodeapp:latest
        imagePullPolicy: Always
        name: nodeapp
        ports:
        - containerPort: 8000
          protocol: TCP
