apiVersion: v1
kind: Service
metadata:
  labels:
    run: nodeapp
  name: nodeapp
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    run: nodeapp
  sessionAffinity: None
